module ReportsHelper

  class Report::ActiveRecord_Relation
	# group bunch of reports according to whether each of the collections
	# generated by the reports intersects with a given collection
	def group_by_collection (intersection_list, &get_list)
	  grouped = Hash.new
	  self.each do |report|
	  	(get_list.call(report) & intersection_list).each do |element|
	  		grouped[element] ? grouped[element] << report : grouped[element] = [report]
	  	end
	  end
	  return grouped
	end
  end

end
